import LegalPage from "@/components/LegalPage";

export const metadata = { title: "Terms of Service - JobFinder AI" };

export default function TermsOfService() {
  return (
    <LegalPage title="Terms of Service" updated="June 17, 2026">
      <section>
        <h2>What you&apos;re buying</h2>
        <p>
          $5 (charged in your local currency at the live exchange rate) gets you 7 days of access to JobFinder AI: live job matching across the sources we query, the
          Application Tracker, Interview Prep, Skills Gap and Salary Intelligence analysis, and (where
          configured) the AI Cover Letter Generator and Interview Coach. Access doesn&apos;t auto-renew - when the
          7 days end you can pay again to continue.
        </p>
      </section>

      <section>
        <h2>What we don&apos;t do</h2>
        <p>
          We don&apos;t guarantee you&apos;ll get interviews or a job offer. We aggregate live postings from public
          job board APIs and match them to your CV - we don&apos;t control those listings, verify every employer,
          or submit applications to them on your behalf beyond opening the listing when you click Apply. We
          don&apos;t contact recruiters or schedule interviews for you automatically; any interview dates you see
          in Interview Prep are ones you entered yourself.
        </p>
      </section>

      <section>
        <h2>AI-generated content</h2>
        <p>
          Cover letters and interview questions generated by the AI Coach are drafts based on the CV and job
          details you provide. Review everything before sending it - we&apos;re not responsible for inaccuracies
          in AI-generated text, and you shouldn&apos;t submit anything you haven&apos;t checked yourself.
        </p>
      </section>

      <section>
        <h2>Your account</h2>
        <p>
          You&apos;re responsible for the accuracy of the information in your CV and for keeping your account
          access to yourself. You must be 18 or older to use this service.
        </p>
      </section>

      <section>
        <h2>Acceptable use</h2>
        <p>
          Don&apos;t use this service to scrape, resell, or redistribute the job listings we surface, to submit
          false information to employers, or to abuse the AI features (e.g. generating spam). We reserve the
          right to suspend accounts that misuse the service.
        </p>
      </section>

      <section>
        <h2>Refunds</h2>
        <p>See our <a href="/refund-policy" className="text-violet-400 hover:text-violet-300">Refund Policy</a> - short version: 30-day money-back guarantee, no questions asked.</p>
      </section>

      <section>
        <h2>Liability</h2>
        <p>
          The service is provided as-is. We aren&apos;t liable for job outcomes, third-party listing accuracy, or
          decisions made based on AI-generated content or our match scores, salary estimates, or skills gap
          analysis - these are informational tools, not guarantees.
        </p>
      </section>

      <section>
        <h2>Changes</h2>
        <p>We may update these terms; continued use after a change means you accept the update.</p>
      </section>
    </LegalPage>
  );
}
